version: 0.17.1-dev.{build}

environment:
  matrix:
    - generator: "MSYS Makefiles"  # MinGW-w64 gcc-5.1.0 64 bit
      Arch : Win64
    - generator: "MSYS Makefiles"  # MinGW-w64 gcc-5.1.0 32 bit
      Arch: i686
    - generator: "Visual Studio 12"
      Arch: Win32
    - generator: "Visual Studio 12 Win64"
      Arch: Win64
    - generator: "Visual Studio 14"
      Arch: Win32
    - generator: "Visual Studio 14 Win64"
      Arch : Win64
    - generator: "MSYS Makefiles"  # MinGW-w64 gcc-4.8.1 32 bit that comes with appveyor
      Arch : Win32

configuration:
  #- Debug
  - RelWithDebInfo

branches:
  only:
    - master
    - review/*
    - tp/*  # to remove when branch is merged

shallow_clone: true 

cache:
- i686-4.9.2-release-win32-sjlj-rt_v3-rev1.7z
- x86_64-4.9.2-release-win32-seh-rt_v3-rev1.7z

# scripts that are called at very beginning, before repo cloning
init:

before_build:

# scripts that run after cloning repository
install:
  - git clone -q --branch=master https://github.com/QbProg/oce-win-bundle.git C:\projects\oce-win-bundle

build_script:
  - cmd: if "%generator%" == "MSYS Makefiles" (C:\MinGW\msys\1.0\bin\sh --login /c/projects/oce/appveyor-scripts/make-oce-msys.sh)
      else (CALL C:\projects\oce\appveyor-scripts\make-oce-msvc.bat)

test: off

deploy: off
